'''
Created on 16.07.2014

@author: Jimbo
'''

METROPOLIS_HASTINGS = "METROPOLIS_HASTINGS"
ADAPTIVE_METROPOLIS_HASTINGS = "ADAPTIVE_METROPOLIS_HASTINGS"
ADAPTIVE_GIBBS = "ADAPTIVE_GIBBS"
COERCED_ACCEPTANCE_RATE = "COERCED_ACCEPTANCE_RATE"