'''
Created on 16.07.2014

@author: Jimbo
'''

METROPOLIS_HASTINGS = "METROPOLIS_HASTINGS"
ADAPTIVE_METROPOLIS_HASTINGS = "ADAPTIVE_METROPOLIS_HASTINGS"
ADAPTIVE_GIBBS = "ADAPTIVE_GIBBS"
REGIONAL_ADAPTIVE_METROPOLIS_HASTINGS = "REGIONAL_ADAPTIVE_METROPOLIS_HASTINGS"